### ISSUE TITLE
Method 'Insert' in type 'SoundFingerprinting.Extensions.LMDB.LMDBModelService' from assembly 'SoundFingerprinting.Extensions.LMDB, Version=7.9.9.0, Culture=neutral, PublicKeyToken=nul l' does not have an implementation.

### ISSUE THREAD

**Issue by Hamsterland** [Nekromancer/SoundFingerprinting.Extensions.LMDB#5]
```
Unhandled exception. System.TypeLoadException: Method 'Insert' in type 'SoundFingerprinting.Extensions.LMDB.LMDBModelService' from assembly 'SoundFingerprinting.Extensions.LMDB, Version=7.9.9.0, Culture=neutral, PublicKeyToken=nul
l' does not have an implementation.
   at Program.<Main>$(String[] args)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at Program.<Main>$(String[] args)
   at Program.<Main>(String[] args)
```
From
```cs
async Task CreateFingerprintsFromFile(string path)
{
    var track = new TrackInfo(path, path, null!);
    
    var fingerprints = await FingerprintCommandBuilder.Instance
        .BuildFingerprintCommand()
        .From(path)
        .Hash();

    Console.WriteLine($"{path}: Generate hashes {fingerprints}");
    modelService.Insert(track, fingerprints.Audio);
}
```

**Comment by Hamsterland** [comment]
I think this just needs to be updated to support 8.7.0

**Comment by jakoss** [comment]
Since the SoundFingerprint db adapter is not stable the version of LMDB extension is bound the particular version of the library itself. I'll see what i can do about the update

**Comment by jakoss** [comment]
I updated the library to support 8.7.0 version. Beware that it only supports audio fingerprinting. Using any Video query or insert will result in `NotSupportedException`
